attack: null
batch_size: 64
compute_backend: cpu
config: config.py
data_distribution: iid
dataset: mnist
defense: null
epochs: 50
fl_type: classical
ibmq_backend: ibmq_qasm_simulator
local_epochs: 5
lr: 0.01
model: cnn
n_qubits: 4
resume: false
seed: 42
shots: 1024
verbosity: 1
